# Generated by Django 5.2.11 on 2026-05-05 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_added_at_cartitem_date_added_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationcache',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='products_us_user_id_f4ae36_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='date_added',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.posting'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RecommendationCache',
        ),
    ]
